### ISSUE TITLE
uniformly hangs the R session

### ISSUE THREAD

**Issue by acfrery** [stla/uniformly#1]
Hello,

Loading "uniformly" (version 0.5.0) hangs R. The command
> library("uniformly")
keeps running forever.

Also, running an individual function without loading the library, as
> uniformly::runif_in_annulus(100, c(0,0), 1, 2)
keeps running forever.

My R version is
> version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          3.1                         
year           2023                        
month          06                          
day            16                          
svn rev        84548                       
language       R                           
version.string R version 4.3.1 (2023-06-16)
nickname       Beagle Scouts

I'm running RStudio Version 2023.06.2+561 (2023.06.2+561) on a MacBook Pro (14-inch, 2021) with Ventura 13.5.2 (22G91). The same issue occurs if I run R in a console.

Thanks for your attention,

Alejandro

**Comment by stla** [comment]
Sorry, no idea. There's no problem with the CRAN checks. Did you try to reinstall the package?

**Comment by acfrery** [comment]
I found the source of the problem: rgl, which is required by uniformly, is broken after an update.
Thanks!
Alejandro
